spring:
  config:
    name: COMMON

### Spring 공통 문서 관리
common:
  api-doc:
    title: "AI Insight Agent"
    description: "AI Insight API"
    version: "1.0"
    contact-email: "demo@exmple.com"

  ### API 로깅 인터셉터 설정
  api-logging:
    enabled: true
    include-paths:
      - /api/**
    exclude-paths:
      - /api/docs/**
      - /api/swagger-ui/**

### Spring 문서 관리
springdoc:
  server:
    url: http://localhost:28080
#    url: https://localhost
    description: Dev server
  api-docs:
    enabled: true
  swagger-ui:
    path: /api
    enabled: true
  # 일반화된 응답 사용 여부 결정(Handler 충돌방지)
  override-with-generic-response: false