### 서버 관리
server:
  ### 내장 WAS 관리
  port: 28080

logging:
  level:
    root: INFO

### 스프링 관리
spring:
  config:
    name: AIA-APP
    import: application-common.yml
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/analysis_platform?rewriteBatchedStatements=true
    username: sa
    password:
  ### JPA 관리
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
  ai:
    gemini:
      api-key: ${OPENAI_API_KEY}
      model: gemini-2.5-flash
      temperature: 0.7
      base-url: https://generativelanguage.com
      completions-path: v1beta2/models/{model}/completions
