### 서버 관리
server:
  ### 내장 WAS 관리
  port: 28080

logging:
  level:
    root: INFO

### 스프링 관리
spring:
  config:
    name: AIA-APP
    import: application-common.yml
  profiles:
    active: local
  ai:
    gemini:
      api-key: YOUR_GEMINI_API_KEY
      model: gemini-1.5-pro
      temperature: 0.7
      base-url: https://generativelanguage.com
      completions-path: v1beta2/models/{model}/completions
