### 서버 관리
server:
  ### 내장 WAS 관리
  port: 28080

logging:
  level:
    root: INFO

### 스프링 관리
spring:
  config:
    name: AIA-APP
    import: application-common.yml
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/analysis_platform?rewriteBatchedStatements=true
    username: sa
    password:
  ### JPA 관리
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
  ai:
    gemini:
      models:
        - id: m00
          name: gemini-2.5-flash
          api-key: ${GEMINI_API_KEY_0:}
        - id: m01
          name: gemini-2.5-flash
          api-key: ${GEMINI_API_KEY_1:}
        - id: m02
          name: gemini-2.5-flash
          api-key: ${GEMINI_API_KEY_2:}
        - id: m03
          name: gemini-2.5-flash
          api-key: ${GEMINI_API_KEY_3:}
        - id: m04
          name: gemini-2.5-flash
          api-key: ${GEMINI_API_KEY_4:}
        - id: m05
          name: gemini-2.5-flash
          api-key: ${GEMINI_API_KEY_5:}
        - id: m06
          name: gemini-2.5-flash
          api-key: ${GEMINI_API_KEY_6:}
        - id: m07
          name: gemini-2.5-flash
          api-key: ${GEMINI_API_KEY_7:}
        - id: m08
          name: gemini-2.5-flash
          api-key: ${GEMINI_API_KEY_8:}
        - id: m09
          name: gemini-2.5-flash
          api-key: ${GEMINI_API_KEY_9:}
      temperature: 0.7
      base-url: https://generativelanguage.com
      completions-path: v1beta2/models/{model}/completions
      max-output-tokens: 8192

aiinsight:
  request:
    queue:
      worker-count: 10
      queue-capacity: 100
      request-timeout-seconds: 60
      shutdown-timeout-seconds: 30
